// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package layer3

import (
	"github.com/ossf/gemara/common"
	"github.com/ossf/gemara/layer1"
	"github.com/ossf/gemara/layer2"
)

// Core Document Structure
type Policy struct {
	Metadata common.Metadata `json:"metadata" yaml:"metadata"`

	OrganizationID string `json:"organization-id" yaml:"organization-id"`

	Title string `json:"title" yaml:"title"`

	Purpose string `json:"purpose" yaml:"purpose"`

	Contacts Contacts `json:"contacts" yaml:"contacts"`

	Scope Scope `json:"scope" yaml:"scope"`

	ImportedPolicies []ImportedPolicy `json:"imported-policies,omitempty" yaml:"imported-policies,omitempty"`

	ImplementationPlan ImplementationPlan `json:"implementation-plan,omitempty" yaml:"implementation-plan,omitempty"`

	GuidanceReferences []PolicyMapping `json:"guidance-references,omitempty" yaml:"guidance-references,omitempty"`

	ControlReferences []PolicyMapping `json:"control-references,omitempty" yaml:"control-references,omitempty"`
}

type Contacts struct {
	Author common.Contact `json:"author" yaml:"author"`

	Responsible []common.Contact `json:"responsible" yaml:"responsible"`

	Accountable []common.Contact `json:"accountable" yaml:"accountable"`

	Consulted []common.Contact `json:"consulted,omitempty" yaml:"consulted,omitempty"`

	Informed []common.Contact `json:"informed,omitempty" yaml:"informed,omitempty"`
}

type Scope struct {
	// geopolitical boundaries such as region names or jurisdictions
	Boundaries []string `json:"boundaries,omitempty" yaml:"boundaries,omitempty"`

	// names of technology categories or services
	Technologies []string `json:"technologies,omitempty" yaml:"technologies,omitempty"`

	// names of organizations who make the listed technologies available
	Providers []string `json:"providers,omitempty" yaml:"providers,omitempty"`
}

// ImportedPolicy represents a reference to another policy that is imported wholesale
type ImportedPolicy struct {
	ReferenceId string `json:"reference-id" yaml:"reference-id"`
}

type ImplementationPlan struct {
	// The process through which notified parties should be made aware of this policy
	NotificationProcess string `json:"notification-process,omitempty" yaml:"notification-process,omitempty"`

	NotifiedParties []NotificationGroup `json:"notified-parties,omitempty" yaml:"notified-parties,omitempty"`

	EvaluationTimeline ImplementationDetails `json:"evaluation-timeline" yaml:"evaluation-timeline"`

	Evaluators []common.Actor `json:"evaluators,omitempty" yaml:"evaluators,omitempty"`

	EnforcementTimeline ImplementationDetails `json:"enforcement-timeline" yaml:"enforcement-timeline"`

	EnforcementMethods []EnforcementMethod `json:"enforcement-methods,omitempty" yaml:"enforcement-methods,omitempty"`

	// The consequence that will be applied in the event that noncompliance is detected
	NoncomplianceConsequence string `json:"noncompliance-consequence,omitempty" yaml:"noncompliance-consequence,omitempty"`
}

type NotificationGroup string

type ImplementationDetails struct {
	Start common.Datetime `json:"start" yaml:"start"`

	End common.Datetime `json:"end,omitempty" yaml:"end,omitempty"`

	Notes string `json:"notes" yaml:"notes"`
}

type EnforcementMethod string

// Layer 3 specific mapping that extends common Mapping with modifications
type PolicyMapping struct {
	ReferenceId string `json:"reference-id" yaml:"reference-id"`

	ControlModifications []ControlModifier `json:"control-modifications,omitempty" yaml:"control-modifications,omitempty"`

	GuidelineModifications []GuidelineModifier `json:"guideline-modifications,omitempty" yaml:"guideline-modifications,omitempty"`
}

// Modifier Types
type ControlModifier struct {
	Id string `json:"id,omitempty" yaml:"id,omitempty"`

	TargetId string `json:"target-id" yaml:"target-id"`

	ModType ModType `json:"modification-type" yaml:"modification-type"`

	ModificationRationale string `json:"modification-rationale" yaml:"modification-rationale"`

	Overrides *layer2.Control `json:"overrides,omitempty" yaml:"overrides,omitempty"`

	Extensions *ControlExtensions `json:"extensions,omitempty" yaml:"extensions,omitempty"`

	AssessmentRequirementModifications []AssessmentRequirementModifier `json:"assessment-requirement-modifications,omitempty" yaml:"assessment-requirement-modifications,omitempty"`
}

type ModType string

type ControlExtensions struct {
	Severity Severity `json:"severity,omitempty" yaml:"severity,omitempty"`

	AutoRemediationAllowed bool `json:"auto-remediation-allowed,omitempty" yaml:"auto-remediation-allowed,omitempty"`

	DeploymentGateAllowed bool `json:"deployment-gate-allowed,omitempty" yaml:"deployment-gate-allowed,omitempty"`
}

type AssessmentRequirementModifier struct {
	Id string `json:"id,omitempty" yaml:"id,omitempty"`

	TargetId string `json:"target-id" yaml:"target-id"`

	ModType ModType `json:"modification-type" yaml:"modification-type"`

	ModificationRationale string `json:"modification-rationale" yaml:"modification-rationale"`

	Overrides *layer2.AssessmentRequirement `json:"overrides,omitempty" yaml:"overrides,omitempty"`

	Extensions *AssessmentRequirementExtensions `json:"extensions,omitempty" yaml:"extensions,omitempty"`
}

type AssessmentRequirementExtensions struct {
	RequiredEvaluators []string `json:"required-evaluators,omitempty" yaml:"required-evaluators,omitempty"`

	OptionalEvaluators []string `json:"optional-evaluators,omitempty" yaml:"optional-evaluators,omitempty"`

	EvidenceRequirements string `json:"evidence-requirements,omitempty" yaml:"evidence-requirements,omitempty"`

	ResolutionStrategy ResolutionStrategy `json:"resolution-strategy,omitempty" yaml:"resolution-strategy,omitempty"`

	EvaluationPoints []EvaluationPoint `json:"evaluation-points,omitempty" yaml:"evaluation-points,omitempty"`
}

type EvaluationPoint string

type GuidelineModifier struct {
	Id string `json:"id,omitempty" yaml:"id,omitempty"`

	TargetId string `json:"target-id" yaml:"target-id"`

	ModType ModType `json:"modification-type" yaml:"modification-type"`

	ModificationRationale string `json:"modification-rationale" yaml:"modification-rationale"`

	Overrides *layer1.Guideline `json:"overrides,omitempty" yaml:"overrides,omitempty"`

	StatementModifications []StatementModifier `json:"statement-modifications,omitempty" yaml:"statement-modifications,omitempty"`
}

type StatementModifier struct {
	Id string `json:"id,omitempty" yaml:"id,omitempty"`

	TargetId string `json:"target-id" yaml:"target-id"`

	ModType ModType `json:"modification-type" yaml:"modification-type"`

	ModificationRationale string `json:"modification-rationale" yaml:"modification-rationale"`

	Overrides *layer1.Statement `json:"overrides,omitempty" yaml:"overrides,omitempty"`
}
