// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package layer1

type Catalog struct {
	Metadata Metadata `json:"metadata,omitempty"`

	FrameworkSections []FrameworkSection `json:"framework-sections,omitempty"`
}

type Metadata struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Description string `json:"description"`

	Version string `json:"version,omitempty"`

	LastModified string `json:"last-modified,omitempty"`

	PublicationDate string `json:"publication-date,omitempty"`

	IssuingBody string `json:"issuing-body,omitempty"`

	MappingReferences []MappingReference `json:"mapping-references,omitempty"`

	Resources []ResourceReference `json:"resources,omitempty"`
}

type MappingReference struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Version string `json:"version"`

	Description string `json:"description,omitempty"`

	Url string `json:"url,omitempty"`
}

type ResourceReference struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Description string `json:"description"`

	Url string `json:"url,omitempty"`

	DocumentType DocumentType `json:"document-type,omitempty"`

	IssuingBody string `json:"issuing-body,omitempty"`

	PublicationDate string `json:"publication-date,omitempty"`
}

type DocumentType string

type FrameworkSection struct {
	Title string `json:"title"`

	Description string `json:"description"`

	Guidelines []Guideline `json:"guidelines,omitempty"`
}

type Guideline struct {
	Id string `json:"id"`

	Title string `json:"title,omitempty"`

	GuidanceText string `json:"guidance-text"`

	GuidanceSource []Resource `json:"guidance-sources,omitempty"`

	GuidelineParts []*Guideline `json:"guidelines-parts,omitempty"`

	// Control mapping to external catalogs
	GuidelineMappings []Mapping `json:"guideline-mapping,omitempty"`
}

type Resource struct {
	ReferenceId string `json:"reference-id"`

	Remarks string `json:"remarks,omitempty"`
}

type Mapping struct {
	ReferenceId string `json:"reference-id"`

	Identifiers []string `json:"identifiers"`

	// Adding context about this particular mapping and why it was mapped.
	Remarks string `json:"remarks,omitempty"`
}
