// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package layer1

import (
	"github.com/ossf/gemara/common"
)

// Guidance represents a Layer 1 guidance document
type Guidance struct {
	Metadata common.Metadata `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	Title string `json:"title" yaml:"title"`

	DocumentType DocumentType `json:"document-type" yaml:"document-type"`

	FrontMatter string `json:"front-matter,omitempty" yaml:"front-matter,omitempty"`

	Exemptions []Exemption `json:"exemptions,omitempty" yaml:"exemptions,omitempty"`

	Families []common.Family `json:"families" yaml:"families"`

	Guidelines []Guideline `json:"guidelines" yaml:"guidelines"`
}

type DocumentType string

// Exemption represents an exemption with a reason and optional redirect
type Exemption struct {
	Reason string `json:"reason" yaml:"reason"`

	Redirect common.Mapping `json:"redirect,omitempty" yaml:"redirect,omitempty"`
}

// Guideline represents a single guideline within a guidance document
type Guideline struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Objective string `json:"objective,omitempty" yaml:"objective,omitempty"`

	FamilyId string `json:"family-id,omitempty" yaml:"family-id,omitempty"`

	Recommendations []string `json:"recommendations,omitempty" yaml:"recommendations,omitempty"`

	// Extends allows you to add supplemental guidance within a local guidance document
	// like a control enhancement or from an imported guidance document.
	Extends common.SimpleMapping `json:"extends,omitempty" yaml:"extends,omitempty"`

	Rationale *Rationale `json:"rationale,omitempty" yaml:"rationale,omitempty"`

	Statements []Statement `json:"statements,omitempty" yaml:"statements,omitempty"`

	GuidelineMappings []common.Mapping `json:"guideline-mappings,omitempty" yaml:"guideline-mappings,omitempty"`

	PrincipleMappings []common.Mapping `json:"principle-mappings,omitempty" yaml:"principle-mappings,omitempty"`

	SeeAlso []common.SimpleMapping `json:"see-also,omitempty" yaml:"see-also,omitempty"`
}

// Rationale provides contextual information to help with development and understanding of
// guideline intent.
type Rationale struct {
	Importance string `json:"importance" yaml:"importance"`

	Goals []string `json:"goals" yaml:"goals"`
}

// Statement represents a sub-statement within a guideline
type Statement struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title,omitempty" yaml:"title,omitempty"`

	Text string `json:"text" yaml:"text"`

	Recommendations []string `json:"recommendations,omitempty" yaml:"recommendations,omitempty"`
}
